[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'
[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'powerman/vim-plugin-AnsiEsc'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'vim-scripts/errormarker.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
on_source = ['vimshell.vim']

# ファイル検索
[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

# ローカル設定読み込み
[[plugins]]
repo = 'thinca/vim-localrc'

# カッコ系
[[plugins]]
repo = 'tpope/vim-surround'

# コメントアウト
[[plugins]]
repo = 'sakuraiyuta/commentout.vim'

# Git系
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'airblade/vim-gitgutter'

# HTML
[[plugins]]
repo = 'mattn/emmet-vim'

# CSS
[[plugins]]
repo = 'cakebaker/scss-syntax.vim'

# Vue
[[plugins]]
repo = 'posva/vim-vue'

# JSX
[[plugins]]
repo = 'pangloss/vim-javascript'
repo = 'mxw/vim-jsx'

# Perl
[[plugins]]
repo = 'moznion/vim-cpanfile'
[[plugins]]
repo = 'moznion/syntastic-cpanfile'
[[plugins]]
repo = 'y-uuki/perl-local-lib-path.vim'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'Shougo/ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-around'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'

[[plugins]]
repo = 'shun/ddc-vim-lsp'

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'

[[plugins]]
repo = 'matsui54/denops-signature_help'

