[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
on_source = ['vimshell.vim']

# Nerdtreeでタブで開くときにタイトルをNerdTreeにしないやつ
[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'
