[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
on_source = ['unite.vim', 'vimshell.vim']

[[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = 'context_filetype.vim'

# Nerdtreeでタブで開くときにタイトルをNerdTreeにしないやつ
[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'
