[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'
[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'vim-scripts/errormarker.vim'

# ファイル検索
[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

# ローカル設定読み込み
[[plugins]]
repo = 'thinca/vim-localrc'

# カッコ系
[[plugins]]
repo = 'tpope/vim-surround'

# コメントアウト
[[plugins]]
repo = 'sakuraiyuta/commentout.vim'

# Git系
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'airblade/vim-gitgutter'

# HTML
[[plugins]]
repo = 'mattn/emmet-vim'

# CSS
[[plugins]]
repo = 'cakebaker/scss-syntax.vim'

# Vue
[[plugins]]
repo = 'posva/vim-vue'

# JSX
[[plugins]]
repo = 'pangloss/vim-javascript'
repo = 'mxw/vim-jsx'

# Perl
[[plugins]]
repo = 'moznion/vim-cpanfile'
[[plugins]]
repo = 'moznion/syntastic-cpanfile'
[[plugins]]
repo = 'y-uuki/perl-local-lib-path.vim'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = [ 'roxma/nvim-yarp', 'roxma/vim-hug-neovim-rpc' ]
on_i = 1
hook_source = '''
let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'
