brew 'wget'
brew 'openssl'
brew 'git'
brew 'git-flow'
brew 'tig'
brew 'tree'
brew 'jq'
brew 'plenv'
brew 'rbenv'
brew 'goenv'
brew 'nodenv'
brew 'readline'
brew 'ag'
brew 'tmux'
brew 'peco'

brew 'universal-ctags', args: ['HEAD']

# vim
brew 'vim'

# for ddc.vim
brew 'deno'

tap 'sanemat/font'
brew 'ricty', args: ['with-powerline']
